### ISSUE TITLE
Absturz bei Einkapselung

### ISSUE THREAD

**Issue by davidflury** [holruum/holruum#1]
Beim Einkapseln eines Eckfelds ohne direkten Nachbar stürzt das Spiel ab.
Fehlermeldung:

12345 | [UNEXPECTED] java.lang.IllegalArgumentException: Book object is null and cannot be processed.java.lang.IllegalArgumentException: Book object is null and cannot be processed.at io.airbrake.NullPointerException.callInstanceFieldOfNull(NullPointerException.java:45)at io.airbrake.NullPointerException.main(NullPointerException.java:12)
-- | --

**Comment by davidflury** [comment]
Please fix
